# Generated by Django 5.2.7 on 2025-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
